name: Login and logout container registry
description: Login and logout container registry
author: Kevin Tijssen (TNO)

inputs:
  command: 
    description: 'What do you want to do? (login/logout)'
    required: true
    default: 'login'
  username:
    description: 'Username to log in to the registry'
    required: false
  password: 
    description: 'password that belongs to the username'
    required: false
  registry:
    description: 'The name of the registry server'
    required: false
    default: ''

runs:
  using: "composite"
  steps:

    - name: Buildah Build / Push / Build & Push
      shell: bash
      run: |
        case ${{ inputs.command }} in
            (login|logout) ;;
            (*) echo "ERROR: invalid variable '${{ inputs.command }}' for 'command'. Allowed variables are 'login or logout'";
            exit 1;;
        esac

        function login() {
          buildah login -u ${{ inputs.username }} -p ${{ inputs.password }} ${{ inputs.registry }}
        }

        function logout() {
          buildah logout ${{ inputs.registry }}
        }

        if [[ ${{ inputs.command }} == "login" ]]; then
          login
          exit 0
        else
          logout
          exit 0
        fi